# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Adis Osmonov
tagline:          'Adis Osmonov'
description:      'Ruby / Ruby on Rails'
url:              https://adis.osmonov.com/
baseurl:          /

author:
  name:           'Adis Osmonov'
  url:            https://adis.osmonov.com/

paginate:         5
google_analytics: 'UA-124183848-1'
emailme:          mailto:adis@osmonov.com

github:
  repo:           https://github.com/adis-io/adis-io.github.io/
